### ISSUE TITLE
could not find function "enrichment_barplot"

### ISSUE THREAD

**Issue by marce-sarrias** [ycl6/GO-Enrichment-Analysis-Demo#3]
Hello,

I'm trying to make a bar plot of the enriched go terms as shown in [https://ycl6.github.io/GO-Enrichment-Analysis-Demo/2_topGO.html](https://github.com/ycl6/topGO-feat/issues/url) but it's not working.

I have tried installing the github version which should have the enrichment_barplot function but it's still not working. Any advice?

devtools::install_github("ycl6/topGO-feat", ref = "v2.41.0-barplot", force = TRUE)
library(topGO)
png(paste0(outTitle, "_up.png"), width = 8, height = 6, units = "in", res = 300)
enrichment_barplot(up_GOdata, up_Res, showTerms = 20, numChar = 50, orderBy = "Scores",
title = paste0("GO-", ontology," ORA of up-regulated genes"))
invisible(dev.off())

Error in enrichment_barplot(up_GOdata, up_Res, showTerms = 20, numChar = 50, :
could not find function "enrichment_barplot"

Thank you,

Marcela

**Comment by ycl6** [comment]
Hi @marce-sarrias I've responded you here: https://github.com/ycl6/topGO-feat/issues/4

**Comment by ycl6** [comment]
This is now resolved
